crm/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('orders/', views.OrderListView.as_view(), name='home'),
    path('orders/all/', views.AllOrderListView.as_view(), name='all'),
    path('orders/on_pay/', views.WaitPayOrderListView.as_view(), name='on_pay'),
    path('orders/finish/', views.FinishOrderListView.as_view(), name='finish'),
    path('orders/addorder/', views.AddOrder.as_view(), name='addorder'),
    path('orders/delete/<int:order_id>/', views.DeleteOrder.as_view(), name='delete'),
    path('orders/updateproduct/<int:product_id>/', views.UpdateProduct.as_view(), name='upd_product'),
    path('orders/updateproduct/delete/<int:image_id>/', views.DeleteImage.as_view(), name='delete_image'),
    path('orders/update/<int:order_id>/', views.update, name='upd'),
    path('orders/update/delete/<int:product_id>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('logistic/', views.DeliveryStatus.as_view(), name='status_delivery'),
    path('logistic/sp', views.ProductStatus.as_view(), name='status_product'),
    # path('logistic/sp/delete/<int:packed_image_id>/', views.DeletePackedImage.as_view(), name='delete_packedimage'),
    path('logistic/archive', views.DeliveryListView.as_view(), name='archive'),
    # path('logistic/status_delivery/delete/<int:logistic_image_id>/', views.DeleteLogisticImage.as_view(), name='delete_logistic_image'),
    path('logistic/delete/<int:logistic_id>/', views.DeleteDelivery.as_view(), name='delete_logistic'),
    path('save_notes_product', views.save_notes_product, name='save_notes_product'),
    path('save_notes_delivery', views.save_notes_delivery, name='save_notes_delivery'),
    path('load_delivery_info', views.load_delivery_info, name='load_delivery_info'),
    path('change_logistic_status', views.change_logistic_status, name='change_logistic_status'),
    path('change_status_paid', views.change_status_paid, name='change_status_paid'),
    path('change_status_arrive', views.change_status_arrive, name='change_status_arrive'),
    path('get_price', views.get_price, name='get_price'),
    path('save_image', views.save_image, name='save_image'),
    path('save_image_product', views.save_image_product, name='save_image_product'),
    path('delete_image_product', views.delete_image_product, name='delete_image_product'),
    path('delete_notes_product', views.delete_notes_product, name='delete_notes_product'),
    path('delete_image_logistic', views.delete_image_logistic, name='delete_image_logistic'),
    path('delete_notes_delivery', views.delete_notes_delivery, name='delete_notes_delivery'),
    path('logistic/add_delivery', views.AddDelivery.as_view(), name='add_delivery'),
    path('show_product_info', views.show_product_info, name='show_product_info'),
    path('logistic/update_delivery/<int:logistic_id>/', views.UpdateDelivery.as_view(), name='update_delivery'),
    path('account/add_acc/', views.AddAccount.as_view(), name='add_account'),
    path('account/delete/<int:account_id>/', views.DeleteAccount.as_view(), name='delete_account'),
    path('ajax_change_delivery', views.change_delivery, name='change_delivery'),
    path('change_date', views.change_datetime, name='change_date'),
    path('notifications', views.ViewNotifications.as_view(), name='notifications'),
    path('finance', views.FinanceList.as_view(), name='finance_list'),
    path('finance/add_spending/', views.AddSpending.as_view(), name='add_spending'),
    path('finance/spendings/', views.SpendingList.as_view(), name='list_spendings'),
    path('finance/update_spendings/<int:spending_id>/', views.SpendingUpdate.as_view(), name='update_spending'),
    path('finance/create_invoice/', views.create_invoice, name='create_invoice'),
    path('ajax_get_course', views.getcourse, name='get_course'),
    path('ajax_add_product', views.add_product, name='add_product'),
    path('ajax_get_notification', views.get_notification, name='get_notification'),
    path('ajax_read_notification', views.read_notification, name='read_notification'),
    path('ajax_create_invoice', views.create_invoice, name='create_invoice'),
    path('ajax_read_all_notification', views.read_all_notification, name='read_all_notification')
]

crm/crm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls', namespace='login')),
    path('manager/', include('core.urls', namespace='core')),
    path('sendings/', include('sendings.urls', namespace='sendings')),
    path('call/', include('clients.urls', namespace='clients')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    # path('', views.OrderChartView.as_view(), name='home'),
    path('', views.chart, name='home'),
]

crm/dashboard/forms.py
from django import forms

crm/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count, Sum
from django.db.models.functions import TruncDay
from django.shortcuts import render
from core.models import Order
from crm.settings import LOGIN_URL
from dashboard.filters import OrderChartFilter
""".values(day=TruncDay('date_create')).annotate(Count('id'), Sum('total_price_rub'))"""


@login_required(login_url=LOGIN_URL)
def chart(request):
    filter = OrderChartFilter(request.GET, queryset=Order.objects.all())
    context = {'users': [
        {
            'id': obj.id,
            'username': obj.username,
            'summa': sum([i.total_price_rub for i in filter.qs.filter(owner=obj) if i.status == "Завершен"])
        }
        for obj in User.objects.all()],
        'filter': filter,
        'complete': filter.qs.filter(status='Завершен').count(),
        'inwork': filter.qs.filter(status='Оформление').count(),
        'onpay': filter.qs.filter(status='На оплату').count(),
        'dataset_complete': filter.qs.filter(status='Завершен').values(day=TruncDay('date_create')).annotate(Count('id'), Sum('total_price_rub')),
        'dataset_all': filter.qs.values(day=TruncDay('date_create')).annotate(Count('id'), Sum('total_price_rub')),
        'total_sum': filter.qs.aggregate(Sum('total_price_rub'))
    }
    return render(request, 'dashboard/charts.html', context)


# class OrderChartView(FilterView):
#     model = Order
#     template_name = 'dashboard/order_chart.html'
#     filterset_class = OrderChartFilter
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['title'] = 'Список заказов'
#
#         context['users'] = [
#             {
#                 'id': obj.id,
#                 'username': obj.username,
#                 'summa': sum([i.total_price_rub for i in obj.order_set.all() if i.status == "Завершен"])
#             }
#             for obj in User.objects.all()
#         ]
#
#         context['form'] = OrderChartFilter.form
#         # print([i.order_set.all() for i in context['users']])
#         return context

crm/templates/dashboard/charts.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-lg-12 secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
<div class="col">
  <br>
    <button class="btn btn-outline-secondary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Фильтры</button>

    <div class="offcanvas offcanvas-end" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
    <div class="offcanvas-header">
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
    </div>
    <div class="offcanvas-body">
    <form method="get">
        {{ filter.form|crispy }}
        <input type="submit" />
    </form>
    </div>
    </div>
</div>
    <hr>
<div class="row">
    <div class="col hei" style="margin: 2rem; padding: 2rem; box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0.5); background: linear-gradient(90deg, rgba(207,242,191,1) 0%, rgba(207,242,191,1) 42%, rgba(0,255,158,1) 100%);">
        <a href="{% url 'core:finish' %}">
            <h3>Завершенные: {{ complete }}</h3>
        </a>
    </div>
    <div class="col hei" style="margin: 2rem; padding: 2rem; box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0.5); background: linear-gradient(90deg, rgba(238,151,189,1) 0%, rgba(234,209,220,1) 50%, rgba(238,151,189,1) 100%);">
        <a href="{% url 'core:all' %}">
            <h3>Оформляются: {{ inwork }}</h3>
        </a>
    </div>
    <div class="col hei" style="margin: 2rem; padding: 2rem; box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0.5); background: linear-gradient(90deg, rgba(57,159,255,1) 0%, rgba(187,221,253,1) 50%, rgba(187,221,253,1) 100%);">
        <a href="{% url 'core:on_pay' %}">
            <h3>Ожидают отправки: {{ onpay }}</h3>
        </a>
    </div>
</div>
    <div class="row">
    <div class="col total_sum" style="margin: 2rem; padding: 2rem; box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0.5); background: linear-gradient(90deg, rgba(207,242,191,1) 0%, rgba(207,242,191,1) 42%, rgba(0,255,158,1) 100%);">
        <h3>Общая сумма заказов: {{ total_sum.total_price_rub__sum|floatformat:2 }}</h3>
    </div>
</div>
<div class="row">
<div class="col-xs-12 col-sm-6 hei">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>

<canvas id="chart" width="400" height="400"></canvas>
<script>
  window.onload = function () {
  // We render via Django template
  var data = [
    {% for item in data %}
      parseFloat({{ item.summa }}),
    {% endfor %}
  ]

  // We render via Django template
  var labels = [
    {% for item in data %}
      "{{ item.date }}",
    {% endfor %}
  ]

  console.log(data);
  console.log(labels);
let ctx = document.getElementById("chart").getContext("2d");

let chart = new Chart(ctx, {
  type: "bar",
  data: {
     labels: [{% for obj in dataset_all %}"{{obj.day}}",{% endfor %}],
     datasets: [
        {
          label: 'Все заказы',
          data: [{% for obj in dataset_all %}parseFloat({{obj.total_price_rub__sum}}),{% endfor %}],
          backgroundColor: [
                "#FF6384",
            ],
          borderColor: "#417690",
        },
        {
          label: 'Завершенные заказы',
          data: [{% for obj in dataset_complete %}parseFloat({{obj.total_price_rub__sum}}),{% endfor %}],
          backgroundColor: [
                "#399fff",
            ],
          borderColor: "#417690",
        }
     ]
  },
  options: {
        scales: {
            y: {
              beginAtZero: true
            }},
        animation: true,
        plugins: {
          legend: {
            display: true
          },
          tooltip: {
            enabled: true
          },

        }
      }
});
}
</script>
</div>
<div class="col-xs-12 col-sm-6">
    <canvas id="oilChart" width="400" height="400"></canvas>
    <script>
        var oilCanvas = document.getElementById("oilChart");

var oilData = {
    labels: [{% for user in users %}"{{user.username}}",{% endfor %}],
    datasets: [
        {
            data: [{% for user in users %}parseFloat({{user.summa}}),{% endfor %}],
            backgroundColor: [
                "#FF6384",
                "#399fff",
                "#84FF63",
                "#8463FF",
                "#6384FF"
            ]
        }]
};

var pieChart = new Chart(oilCanvas, {
  type: 'pie',
  data: oilData
});
    </script>
</div>
</div>
</div>
{% endblock %}