crm/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('orders/', views.OrderListView.as_view(), name='home'),
    path('orders/all/', views.AllOrderListView.as_view(), name='all'),
    path('orders/on_pay/', views.WaitPayOrderListView.as_view(), name='on_pay'),
    path('orders/finish/', views.FinishOrderListView.as_view(), name='finish'),
    path('orders/addorder/', views.AddOrder.as_view(), name='addorder'),
    path('orders/delete/<int:order_id>/', views.DeleteOrder.as_view(), name='delete'),
    path('orders/updateproduct/<int:product_id>/', views.UpdateProduct.as_view(), name='upd_product'),
    path('orders/updateproduct/delete/<int:image_id>/', views.DeleteImage.as_view(), name='delete_image'),
    path('orders/update/<int:order_id>/', views.update, name='upd'),
    path('orders/update/delete/<int:product_id>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('logistic/', views.DeliveryStatus.as_view(), name='status_delivery'),
    path('logistic/sp', views.ProductStatus.as_view(), name='status_product'),
    # path('logistic/sp/delete/<int:packed_image_id>/', views.DeletePackedImage.as_view(), name='delete_packedimage'),
    path('logistic/archive', views.DeliveryListView.as_view(), name='archive'),
    # path('logistic/status_delivery/delete/<int:logistic_image_id>/', views.DeleteLogisticImage.as_view(), name='delete_logistic_image'),
    path('logistic/delete/<int:logistic_id>/', views.DeleteDelivery.as_view(), name='delete_logistic'),
    path('save_notes_product', views.save_notes_product, name='save_notes_product'),
    path('save_notes_delivery', views.save_notes_delivery, name='save_notes_delivery'),
    path('load_delivery_info', views.load_delivery_info, name='load_delivery_info'),
    path('change_logistic_status', views.change_logistic_status, name='change_logistic_status'),
    path('change_status_paid', views.change_status_paid, name='change_status_paid'),
    path('change_status_arrive', views.change_status_arrive, name='change_status_arrive'),
    path('get_price', views.get_price, name='get_price'),
    path('save_image', views.save_image, name='save_image'),
    path('save_image_product', views.save_image_product, name='save_image_product'),
    path('delete_image_product', views.delete_image_product, name='delete_image_product'),
    path('delete_notes_product', views.delete_notes_product, name='delete_notes_product'),
    path('delete_image_logistic', views.delete_image_logistic, name='delete_image_logistic'),
    path('delete_notes_delivery', views.delete_notes_delivery, name='delete_notes_delivery'),
    path('logistic/add_delivery', views.AddDelivery.as_view(), name='add_delivery'),
    path('show_product_info', views.show_product_info, name='show_product_info'),
    path('logistic/update_delivery/<int:logistic_id>/', views.UpdateDelivery.as_view(), name='update_delivery'),
    path('account/add_acc/', views.AddAccount.as_view(), name='add_account'),
    path('account/delete/<int:account_id>/', views.DeleteAccount.as_view(), name='delete_account'),
    path('ajax_change_delivery', views.change_delivery, name='change_delivery'),
    path('change_date', views.change_datetime, name='change_date'),
    path('notifications', views.ViewNotifications.as_view(), name='notifications'),
    path('finance', views.FinanceList.as_view(), name='finance_list'),
    path('finance/add_spending/', views.AddSpending.as_view(), name='add_spending'),
    path('finance/spendings/', views.SpendingList.as_view(), name='list_spendings'),
    path('finance/update_spendings/<int:spending_id>/', views.SpendingUpdate.as_view(), name='update_spending'),
    path('finance/create_invoice/', views.create_invoice, name='create_invoice'),
    path('ajax_get_course', views.getcourse, name='get_course'),
    path('ajax_add_product', views.add_product, name='add_product'),
    path('ajax_get_notification', views.get_notification, name='get_notification'),
    path('ajax_read_notification', views.read_notification, name='read_notification'),
    path('ajax_create_invoice', views.create_invoice, name='create_invoice'),
    path('ajax_read_all_notification', views.read_all_notification, name='read_all_notification')
]

crm/crm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls', namespace='login')),
    path('manager/', include('core.urls', namespace='core')),
    path('sendings/', include('sendings.urls', namespace='sendings')),
    path('call/', include('clients.urls', namespace='clients')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.LoginUser.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),
    path('registration', views.register, name='register'),
    path('update/<int:user_id>/', views.change_user_info, name='update_user')
]

crm/core/views.py
import asyncio
import datetime
import decimal
import json

from django.db.models import Q
from pytz import timezone

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import dateformat
from django.views import View
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from django.views.generic.base import ContextMixin, TemplateView
from django.views.generic.edit import FormMixin
from django_filters.views import FilterView
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from sorl.thumbnail import get_thumbnail

from core.filters import OrderFilter, ProductFilter, DeliveryFilter, DeliveryListFilter
from core.forms import AddOrderForm, ProductForm, ProductFormSet, \
    ProductFormSetHelper, UpdateOrderForm, DeliveryAddForm, PackedImageForm, \
    LogisticImageForm, AddAccountForm, ProductNotesForm, DeliveryNotesForm, ChangeOrderDateForm, ChangeProductDateForm, \
    ChangeDeliveryDateForm, UpdateOrderFormTest, DateFilterForm, SpendingForm, InvoiceForm
from core.models import Order, Product, Logistics, ImagesProduct, PackedImagesProduct, ImagesLogistics, Account, \
    NotesProduct, NotesDelivery, Notification, FilesProduct, ReadNotification, Spendings
from core.utils import get_course, get_invoice
from crm import settings
from crm.settings import LOGIN_URL


def getcourse(request):
    crs = get_course()
    tz = timezone('Europe/Moscow')
    response = {
        'course': str(crs.course),
        'date': dateformat.format(datetime.datetime.now(tz=tz), settings.DATE_FORMAT).lstrip('0'),
    }

    return HttpResponse(json.dumps(response), content_type='application/json')


def get_notification(request):
    tz = timezone('Europe/Moscow')
    response = {'notification': [{
        'id': notification.pk,
        'owner': notification.owner.username if notification.owner else notification.subject_owner.username,
        'action': notification.action,
        'subject': notification.subject,
        'date': dateformat.format(notification.date_create, settings.DATE_FORMAT).lstrip('0'),
    } for notification in Notification.objects.filter(readed=False, subject_owner=request.user).filter(
        ~Q(notifications__readers__in=[request.user.pk]))]
    }
    return HttpResponse(json.dumps(response), content_type='application/json')


def read_notification(request):
    notification_id = request.POST.get("id").split('_')[-1]
    notification = Notification.objects.get(pk=notification_id)
    read = ReadNotification(notification=notification)
    read.save()
    read.readers.add(request.user)

    response = {'notification': Notification.objects.filter(readed=False, subject_owner=request.user).filter(
        ~Q(notifications__readers__in=[request.user.pk])).count()}
    print(response)

    return HttpResponse(json.dumps(response), content_type='application/json')


def read_all_notification(request):
    notifications = Notification.objects.filter(readed=False, subject_owner=request.user).filter(
        ~Q(notifications__readers__in=[request.user.pk]))
    for notification in notifications:
        read = ReadNotification(notification=notification)
        read.save()
        read.readers.add(request.user)
        print(read)

    response = {'notification': Notification.objects.filter(readed=False, subject_owner=request.user).filter(
        ~Q(notifications__readers__in=[request.user.pk])).count()}
    print(response)

    return HttpResponse(json.dumps(response), content_type='application/json')


class CustomHtmxMixin:
    def dispatch(self, request, *args, **kwargs):
        self.template_htmx = self.template_name
        if not self.request.META.get('HTTP_HX_REQUEST'):
            self.template_name = 'components/include_block.html'
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs['template_htmx'] = self.template_htmx
        return super().get_context_data(**kwargs)


class OrderListView(LoginRequiredMixin, PermissionRequiredMixin, FilterView):
    model = Order
    paginate_by = 16
    template_name = 'core/order_list2.html'
    filterset_class = OrderFilter
    permission_required = 'core.view_order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderFilter.form
        context['title'] = 'Список заказов'
        return context

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.filter(result=False)
        elif self.request.user.has_perm('core.view_order'):
            return Order.objects.filter(result=False).filter(owner=self.request.user)


class AllOrderListView(OrderListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderFilter.form
        context['title'] = 'Список активных заказов'
        return context

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.all()
        elif self.request.user.has_perm('core.view_order'):
            return Order.objects.filter(owner=self.request.user)


class WaitPayOrderListView(OrderListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderFilter.form
        context['title'] = 'Заказы - ожидают оплаты'
        return context

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.filter(status='Ожидает отправки')
        elif self.request.user.has_perm('core.view_order'):
            return Order.objects.filter(status='Ожидает отправки').filter(owner=self.request.user)


class FinishOrderListView(OrderListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderFilter.form
        context['title'] = 'Список завершенных заказов'
        return context

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.filter(result=True)
        elif self.request.user.has_perm('core.view_order'):
            return Order.objects.filter(result=True).filter(owner=self.request.user)


class AddOrder(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Order
    permission_required = 'core.add_order'
    form_class = AddOrderForm
    template_name = 'core/addorder.html'

    # On successful form submission
    def get_success_url(self):
        return reverse('core:upd', args=(self.object.pk,))

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(AddOrder, self).get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Оформить заказ'
        return context


class DeleteOrder(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Order
    permission_required = 'core.delete_order'
    context_object_name = 'order'
    pk_url_kwarg = "order_id"
    success_url = reverse_lazy("core:home")


def _get_form(request, formcls, prefix):
    data = request.POST if prefix in request.POST else None
    return formcls(data, prefix=prefix)


@login_required(login_url=LOGIN_URL)
@permission_required('core.change_order')
def update(request, order_id, *args, **kwargs):
    my_kwargs = {'current_user': request.user}
    data = get_object_or_404(Order, pk=order_id)
    form = UpdateOrderFormTest(instance=data, **my_kwargs)
    form2 = ProductForm()
    helper = ProductFormSetHelper()

    if request.method == 'POST':
        form = UpdateOrderFormTest(request.POST, instance=data, **my_kwargs)
        form2 = ProductForm(request.POST)
        files = ProductForm(request.FILES)
        print(form2.errors)
        # Проверяем валидность форм
        if form.is_valid():
            print('форма1 валидна')
            form.save()

        return redirect('core:upd', order_id=order_id)

    context = {
        'data': data,
        'title': data.marker,
        'order_form': form,
        'product_form': form2,
        'helper': helper,
        'products': []
    }
    for prod in data.product.all():
        context['products'].append({'product': prod, 'images': prod.images.all()})
    return render(request, 'core/order_upd.html', context)


def add_product(request):
    print(request.POST)
    print(request.FILES)
    order_id = request.POST.get("id")
    product_marker = request.POST.get("product_marker")
    name = request.POST.get("name")
    url = request.POST.get("url")
    number_order = request.POST.get("number_order")
    price = request.POST.get("price")
    price_company = request.POST.get("price_company")
    fraht = request.POST.get("fraht")
    fraht_company = request.POST.get("fraht_company")
    quantity = request.POST.get("quantity")
    comment = request.POST.get("comment")
    arrive = True if request.POST.get("arrive") == 'true' else False
    paid = True if request.POST.get("paid") == 'true' else False

    product = Product(product_marker=product_marker, name=name, url=url, number_order=number_order,
                      price=decimal.Decimal(price),
                      price_company=decimal.Decimal(price_company), fraht=decimal.Decimal(fraht),
                      fraht_company=decimal.Decimal(fraht_company), quantity=quantity,

crm/templates/core/AjaxTest.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="secondcolor">
    <button type="button" class="btn" style="background-color:green;">Нажми меня полностью.</button>
    <ul id="seconds">

    </ul>
</div>
{% endblock %}

crm/templates/core/add_account.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}


{% block content %}
{% if form %}
    <div class="col secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
    <form action="{% url 'core:add_account' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>
        {{ form|crispy }}
        <button class="btn btn-secondary" type="submit">Сохранить</button>
    </form>
    <div class="row">
        {% for acc in accounts %}
        <div class="row">
            <hr>
            <div class="col" style="text-align: center;">
            <h1><a href="{% url 'login:update_user' acc.user.pk %}">{{acc.user.username}}</a></h1>
            </div>
        </div>
            {% for account in acc.accounts %}
            <div class="row">
                <div class="col" style="text-align: right;">
                    <h3>{{account}}</h3>
                </div>
                <div class="col">
                        <form method="POST" action="{% url 'core:delete_account' account.pk %}">
                            {% csrf_token %}<input type="submit" class="btn_delete_acc" value="Удалить">
                        </form>
                </div>
            </div>
            {% endfor %}
        {% endfor %}
    </div>
    </div>
{% endif %}
{% endblock %}

crm/templates/core/add_delivery.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% if form %}
    <div class="col secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
        <div id="show_info">
        </div>
<div id="myOverlay"></div>

    <form id="delivery-form" action="{% url 'core:add_delivery' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>

<!--        <h1>Продукты</h1>-->
<!--        {% for product in products %}-->
<!--        <div>-->
<!--        <input type="checkbox">{{ product }}-->
<!--            {% for image in product.images.all %}-->
<!--                {{ image }}-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--        {% endfor %}-->

        {% crispy form %}
    </form>
    </div>
{% endif %}
<script defer>
window.onload = function () {
    const Delivery_form = document.getElementById('delivery-form')
    const volume = document.getElementById('id_volume')
    const weight = document.getElementById('id_weight')
    const density = document.getElementById('id_density')
    const csrf = document.getElementsByName('csrfmiddlewaretoken')
    const order_price = document.getElementById('id_order_price')

    const full_price = document.getElementById('id_full_price')
    const tariff_one_kg = document.getElementById('id_tariff_one_kg')
    const tariff = document.getElementById('id_tariff')
    const insurance = document.getElementById('id_insurance')
    const package_price = document.getElementById('id_package_price')

    tariff_one_kg.addEventListener('input', ()=>{
                        tariff.value = (parseFloat(tariff_one_kg.value) * parseFloat(weight.value)).toFixed(2)
                        full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)
        })

    tariff.addEventListener('input', ()=>{
                    if(tariff.value == ''){
                            tariff.value = 0;
                        }
                    full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)
    })


    insurance.addEventListener('input', ()=>{
                    if(insurance.value == ''){
                            insurance.value = 0;
                        }
                    full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)
    })

    package_price.addEventListener('input', ()=>{
                    if(package_price.value == ''){
                            package_price.value = 0;
                        }
                    full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)
    })

    volume.addEventListener('input', ()=>{
                    const volume_data = volume.value
                    console.log(volume_data)
                    if(weight.value == 0){
                            density.value = 0;
                        }
                    else {
                        density.value = parseFloat((weight.value / volume.value).toFixed(2))
                        }
    })
    weight.addEventListener('input', ()=>{
                    const volume_data = volume.value
                    console.log(volume_data)
                    if(volume.value == 0){
                            density.value = 0;
                        }
                    else {
                        density.value = parseFloat((weight.value / volume.value).toFixed(2))
                        }
    })

    weight.addEventListener('input', ()=>{
                    const volume_data = volume.value
                    console.log(volume_data)
                    if(volume.value == 0){
                            density.value = 0;
                        }
                    else {
                        density.value = parseFloat((weight.value / volume.value).toFixed(2))
                        }
                    tariff.value = (parseFloat(tariff_one_kg.value) * parseFloat(weight.value)).toFixed(2)
                    full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)
    })

};


$(document).on('click', "button[name='add_course']", function () {
                        const exchange_rate = document.getElementById('id_exchange_rate')
                        var token = '{{ csrf_token }}';
                        $.ajax({
                            type: "POST",
                            url: "{% url 'core:get_course' %}",
                            headers: {'X-CSRFToken': token},

                            success: function(response) {
                            console.log(response);
                            new_data =
                                        '<h4 style="color:white;">курс $: ' + response.course + '</h4>' +
                                        '<p class="p-size" style="line-height: 0; color:white; margin:0px;">' + response.date + '</p>'

                            $("#get_course").empty();
                            $("#get_course").append(new_data);
                            exchange_rate.value = parseFloat(response.course)

                            },
                            error: function() {
                                console.log('it broke');
                            },
                        });
                    });



    $('[name="product"]').on( "mouseenter", function(e) {
            var show_info = $(this).attr('rel');
            $("#show_info")
                .css("display", "block")
                .animate({ opacity: 1 }, 198);
            if (e.clientX > 700) {
                    $('#show_info').css({'left': e.clientX - 700, 'top': e.clientY + 10});
                    }
            else {
            $('#show_info').css({'left': e.clientX + 10, 'top': e.clientY + 10});
            }
    $.ajax({
            type        : 'POST',
            url         : "{% url 'core:show_product_info' %}",
            data: {
                id: $(this).attr('value'),
                csrfmiddlewaretoken: '{{ csrf_token }}'
                },

            success:function(response){
               var card_image = '<div class="col">' +
                                '<p class="p-size">' + 'Маркировка: ' + response.marker + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Наименование: ' + response.name + '</p>' +
                                '</div>'


                $("#show_info").empty();
                $('#show_info').append(card_image);
                $.each(response.image, function(k, v) {
                    var img = '<img class="img" src="' + v + '">'
                    $('#show_info').append(img);
                    if (k == 3) {
                    return false;
                    }
                });

          },
    });
});


$('[name="product"]').on( "mouseout", function() {
            $("#show_info").css("display", "none");
            $("#show_info").empty();
});


    $('[name="product"]').click(function() {
    var checked_paid = $(this).is(':checked');
    const order_price = document.getElementById('id_order_price')

    $.ajax({

        type: "POST",
        url: "{% url 'core:get_price' %}",
        data: { checked: checked_paid,
                id: $(this).attr('value'),
                csrfmiddlewaretoken: '{{ csrf_token }}'},

        success: function(response) {
               if (checked_paid) {
                      order_price.value = parseFloat(parseFloat(order_price.value) + parseFloat(response.price)).toFixed(2)

                    } else {
                      order_price.value = parseFloat(parseFloat(order_price.value) - parseFloat(response.price)).toFixed(2)
                    }
        console.log(order_price.value)
        console.log(checked_paid);
        console.log(response.price)
        console.log('it work');
        },

        error: function() {
            console.log('it broke');
        },
    });
});

$("input").focus(function(){
  $(this).select();
});
</script>
{% endblock %}

crm/templates/core/add_spending.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}


{% block content %}
{% if form %}
    <div class="col secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
    <form action="{% url 'core:add_spending' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>
        {{ form|crispy }}
        <button class="btn btn-secondary" type="submit">Сохранить</button>
    </form>
    </div>
{% endif %}
{% endblock %}

crm/templates/core/addorder.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}


{% block content %}
{% if form %}
    <div class="col secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
    <form action="{% url 'core:addorder' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>
        {{ form|crispy }}
        <button class="btn btn-secondary" type="submit">Далее</button>
    </form>
    </div>
{% endif %}
{% endblock %}

crm/templates/core/update_order.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<script src="{% static 'core/js/order.js' %}" defer></script>
<div class="row" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
    <h1 align="center">{{title}}</h1>
    <hr>
<div class="col-xs-12 col-sm-4" style="border-right: 1px solid;">
    <form id="order_form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% crispy order_form %}
        <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="button" class="btn btn-warning"><a href="{% url 'core:delete' data.pk %}">Удалить</a></button>
    </form>
    </form>
</div>
<div class="col-xs-12 col-sm-4" style="border-right: 1px solid;">
    <div class="row">
        <form id="product_form" class="row" name="product" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-error">{{ product_form.non_field_errors }}</div>
            {% crispy product_form helper %}
        </form>
    </div>
    <br>
</div>
{% if data.product.all %}
    <div class="col-xs-12 col-sm-4">
        <div class="accordion accordion-flush" id="accordionFlushExample">
        {% for prod in products %}
            <div class="accordion-item">
            <h2 class="accordion-header">
                {% if prod.product.logistics.all %}
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#acc{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapseOne" style="background-color:#d1dee3;">
                {% else %}
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#acc{{forloop.counter}}" aria-expanded="false" aria-controls="flush-collapseOne">
                {% endif %}
                <div class="row"><a href="{% url 'core:upd_product' prod.product.pk %}">{{prod.product.product_marker}} | {{prod.product.name}} | Оплачен: {% if prod.product.paid %}&#9989;{% else %}&#10060;{% endif %} | На складе {% if prod.product.arrive %}&#9989;{% else %}&#10060;{% endif %}</a></div>
              </button>
            </h2>
            <div id="acc{{forloop.counter}}" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
              <div class="accordion-body">
                  {% for img in prod.images %}
                    {% load thumbnail %}
                        {% thumbnail img.image "100x100" as im %}
                    <!-- Modal -->
                            <a href="{{ img.image.url }}" data-bs-toggle="modal" data-bs-target="#img{{forloop.counter}}_{{prod.product.pk}}">
                                  <img src="{{ im.url }}" class="image-detail">
                            </a>
                                        <div class="modal fade" id="img{{forloop.counter}}_{{prod.product.pk}}" tabindex="-1" aria-labelledby="img{{forloop.counter}}" aria-hidden="true">
                                          <div class="modal-dialog modal-xl">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="exampleModalLabel">{{img.product}}</h1>
                                              </div>
                                              <div class="modal-body">
                                                <img src="{{ img.image.url }}">
                                              </div>
                                              <div class="modal-footer">
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                        {% endthumbnail %}
                  {% endfor %}
                  <hr>
                  {% for file in prod.product.files.all %}
                  {% if '.pdf' in file.filename %}
                      <a href={{file.file.url}} target="_blank"><img width="30px;" src="{% static 'core/image/pdf.png' %}">{{file.filename}}</a>
                  {% else %}
                      <a href={{file.file.url}}><img width="30px;" src="{% static 'core/image/xls.png' %}">{{file.filename}}</a>
                  <br>
                  {% endif %}
                  {% endfor %}
                  <div class="row">
                    <div class="col">
                        <a href="{% url 'core:upd_product' prod.product.pk %}" class="btn_edit">Редактировать</a>
                    </div>
                    <div class="col">
                        <form method="POST" action="{% url 'core:delete_product' prod.product.pk %}" class="form">
                            {% csrf_token %}<input type="submit" class="btn_delete" value="Удалить">
                        </form>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        {% endfor %}
    </div>
    </div>
    {% endif %}
</div>
{% endblock %}