crm/crm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls', namespace='login')),
    path('manager/', include('core.urls', namespace='core')),
    path('sendings/', include('sendings.urls', namespace='sendings')),
    path('call/', include('clients.urls', namespace='clients')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/sendings/urls.py
from django.urls import path
from . import views

app_name = 'sendings'

urlpatterns = [
    path('', views.SendingsStatus.as_view(), name='sendings_list'),
    path('sending_create', views.SendingCreate.as_view(), name='sending_create'),
    path('sending_update/<int:sending_id>/', views.SendingUpdate.as_view(), name='sending_update'),
    path('sending_delete/<int:sending_id>/', views.SendingDelete.as_view(), name='sending_delete'),
    path('ajax_create_carrier', views.create_carrier, name='create_carrier'),
    path('ajax_save_notes_sending', views.save_notes_sending, name='save_notes_sending'),
    path('ajax_delete_notes_sending', views.delete_notes_sending, name='delete_notes_sending'),
    path('ajax_change_sending_status', views.change_sending_status, name='change_sending_status'),
    path('ajax_get_info', views.get_info, name='get_info'),
    path('ajax_show_logistic_info', views.show_logistic_info, name='show_logistic_info'),
    path('ajax_change_sending', views.change_sending, name='change_sending'),

]

crm/sendings/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from core.models import Logistics


class Sending(models.Model):
    AUTO = "Авто"
    AUTO_EXPRESS = "Авто-экспресс"
    RAIL = "Жд"
    AVIA = "Авиа"

    DELIVERY_CHOICES = [
        (AUTO, "Авто"),
        (AUTO_EXPRESS, "Авто-экспресс"),
        (RAIL, "Жд"),
        (AVIA, "Авиа"),
    ]

    marker = models.CharField(max_length=100, verbose_name='Номер отправления')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Создал')
    logistics = models.ManyToManyField(Logistics, verbose_name='Грузы', related_name='sendings')
    weight = models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Вес, кг.', default=0)
    volume = models.DecimalField(decimal_places=3, max_digits=100, verbose_name='Объем', default=0)
    tariff = models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Стоимость доставки $', default=0)
    order_price = models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Стоимость товаров в заказах ¥',
                                      default=0)
    delivery = models.CharField(max_length=100, choices=DELIVERY_CHOICES, default='Авто', null=False,
                                verbose_name='Тип отправления')
    places = models.IntegerField(verbose_name='Количество мест', default=1)
    carrier = models.ForeignKey('Carriers', verbose_name='Перевозчик', related_name='carrier',
                                on_delete=models.SET_NULL, null=True)
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    first_step = models.BooleanField(verbose_name='Отправлен', default=False)
    second_step = models.BooleanField(verbose_name='В Москве', default=False)

    class Meta:
        verbose_name = 'Отправка'
        verbose_name_plural = 'Отправки'
        ordering = ['-id']

    def __str__(self):
        if self.marker:
            return self.marker
        return "без имени"

    def get_absolute_url(self):
        return reverse('sendings', kwargs={'sending_id': self.pk})


class Carriers(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название перевозчика')
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def __str__(self):
        if self.name:
            return self.name
        return "без имени"

    def get_absolute_url(self):
        return reverse('carrier', kwargs={'carrier_id': self.pk})


class NotesSending(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Менеджер')
    sending = models.ForeignKey(Sending, on_delete=models.SET_NULL, null=True, verbose_name='Отправка',
                                related_name='sending_notes')
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['id']

    def __str__(self):
        """
        String for representing the Model object.
        """
        if self.owner:
            return self.owner.username
        else:
            return 'без имени'

    def get_absolute_url(self):
        return reverse('note', kwargs={'note_id': self.pk})

crm/sendings/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils import dateformat
from django.views.generic import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView
from django.views.generic.edit import FormMixin

from core.models import Logistics
from crm import settings
from sendings.filters import SendingFilter
from sendings.forms import SendingCreateForm, CarrierAddForm, SendingNotesForm, SimplySendingForm
from sendings.models import Sending, Carriers, NotesSending


class SendingsStatus(LoginRequiredMixin, FilterView):
    model = Sending
    paginate_by = 16
    template_name = 'sendings/sendings_list.html'

    filterset_class = SendingFilter
    # form_class = LogisticImageForm

    def get_queryset(self):
        return Sending.objects.filter(second_step=False)

    def get_success_url(self):
        return reverse('sendings:status_sending')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = SendingFilter.form
        context['notes_form'] = SendingNotesForm
        context['title'] = 'Отправки'
        context['groups'] = self.request.user.groups.filter(name='logist').exists()
        context['china'] = self.request.user.groups.filter(name='china').exists()
        return context


def change_sending_status(request):
    sending_id = request.POST.get("id")
    sending = Sending.objects.get(pk=sending_id)
    checked = request.POST.get("checked")
    attribut = request.POST.get("attribut").split('-')[0]
    if checked == 'true':
        result = True
    else:
        result = False
    if attribut == 'first_step':
        sending.first_step = result
    elif attribut == 'second_step':
        sending.second_step = result
    sending.save()

    response = {
        'OK': 200
    }
    return JsonResponse(response)


def change_sending(request):
    sending_id = request.POST.get("id").split('_')[-1]
    marker = request.POST.get("marker")
    weight = request.POST.get("weight")
    volume = request.POST.get("volume")
    places = request.POST.get("places")
    sending = Sending.objects.get(pk=sending_id)
    sending.marker, sending.weight, sending.volume = marker, weight, volume
    sending.save()
    response = {
        'marker': marker,
        'sending_id': sending_id,
    }
    print(response)

    return HttpResponse(json.dumps(response), content_type='application/json')


def save_notes_sending(request):
    note = request.POST.get("note")
    sending_id = request.POST.get("id")
    comment = NotesSending(sending=Sending.objects.get(pk=sending_id), comment=note, owner=request.user)
    comment.save()
    print(comment.date_create)
    response = {
        'note': note,
        'sending': sending_id,
        'comment_id': comment.pk,
        'user': request.user.username,
        'date': dateformat.format(comment.date_create, settings.DATE_FORMAT).lstrip('0'),
    }
    print(response)

    return HttpResponse(json.dumps(response), content_type='application/json')


def delete_notes_sending(request):
    notes_id = request.POST.get("id").split('_')[-1]
    print(notes_id)
    comment = NotesSending.objects.get(pk=notes_id)
    comment.delete()
    response = {
        'notes_id': notes_id,
    }
    print(response)
    return HttpResponse(json.dumps(response), content_type='application/json')


class SendingCreate(LoginRequiredMixin, CreateView):
    model = Sending
    form_class = SendingCreateForm
    template_name = 'sendings/sending_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Оформить отправку'
        context['carrier_form'] = CarrierAddForm()
        return context

    def get_success_url(self):
        return reverse('sendings:sendings_list')

    def get_form_kwargs(self):
        kwargs = super(SendingCreate, self).get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


def create_carrier(request):
    carrier_name = request.POST.get("name")
    carrier_comment = request.POST.get("comment")
    print(carrier_name)
    print(carrier_comment)
    carrier = Carriers(name=carrier_name, comment=carrier_comment)
    carrier.save()
    print(carrier)

    response = {
        'carrier_name': carrier.name,
        'carrier_comment': carrier_comment,
        'carrier_id': carrier.pk
    }

    # response = {'ok':200}
    return HttpResponse(json.dumps(response), content_type='application/json')


def get_info(request):
    logistic_id = request.POST.get("id")
    logistic = Logistics.objects.get(pk=logistic_id)
    response = {
        'price': logistic.order_price,
        'weight': logistic.weight,
        'volume': logistic.volume,
        'places': logistic.places
    }

    return JsonResponse(response)


def show_logistic_info(request):
    logistic_id = request.POST.get("id")
    logistic = Logistics.objects.get(pk=logistic_id)

    response = {
        'marker': logistic.marker,
        'delivery_price': float(logistic.tariff),
        'products_price': float(logistic.order_price),
        'owner': logistic.owner.username if logistic.owner else None,
        'weight': float(logistic.weight),
        'volume': float(logistic.volume),
        'density': float(logistic.density),
        'insurance': float(logistic.insurance),
        'user': request.user.username if request.user else None,
    }

    return HttpResponse(json.dumps(response), content_type='application/json')


class SendingUpdate(LoginRequiredMixin, UpdateView):
    model = Sending
    form_class = SendingCreateForm
    pk_url_kwarg = 'sending_id'
    template_name = 'sendings/sending_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменить отправку'
        context['carrier_form'] = CarrierAddForm()
        return context

    def get_success_url(self):
        return reverse('sendings:sendings_list')

    def get_form_kwargs(self):
        kwargs = super(SendingUpdate, self).get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs


class SendingDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Sending
    permission_required = 'sendings.delete_sending'
    context_object_name = 'sending'
    pk_url_kwarg = "sending_id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

crm/templates/sendings/sending_create.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
{% if form %}
    <div class="col secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
        <div id="show_info">
        </div>
<div id="myOverlay"></div>

    <form id="sending-form" action="{% url 'sendings:sending_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>
        {% crispy form %}
    </form>
    </div>
{% endif %}


<div id="modal_add_carrier">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-body">
          <form id="carrier-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-error">{{ form.non_field_errors }}</div>
        {% crispy carrier_form %}
    </form>
      </div>
      <div class="modal-footer">
          <input name='close_modal' type="button" value="закрыть">
      </div>
    </div>
  </div>
</div>

<script defer>
    $('[name="add_carrier"]').on( "click", function(e) {
            $("#modal_add_carrier")
                .css("display", "block")
                .animate({ opacity: 1 }, 198);
    });

    $('input[name="close_modal"]').on( "click", function(e) {
            $("#modal_add_carrier")
                .css("display", "none")
                .animate({ opacity: 1 }, 198);
    });

    $(document).on('submit', "#carrier-form", function (e) {
        e.preventDefault();
        $("#modal_add_carrier").css("display", "none");
        var data = $('#carrier-form').serializeArray();
        var token = '{{ csrf_token }}';
        var formData = new FormData($(this)[0]);
        formData.append('name', data.find(x => x.name === 'name').value);
        formData.append('comment', data.find(x => x.name === 'comment').value);
        console.log(data.find(x => x.name === 'comment').value);
        $.ajax({
                type: "POST",
                url: "{% url 'sendings:create_carrier' %}",
                headers: {'X-CSRFToken': token},
                data: formData,
                async: false,
                  cache: false,
                  contentType: false,
                  processData: false,
                success: function(response) {
                $('#id_carrier').append('<option value=' + response.carrier_id + ' selected >' + response.carrier_name + '</option>');
                $('#carrier-form')[0].reset();
                },
                error: function() {
                    console.log('it broke');
                },
            });
        });




<!--    tariff.addEventListener('input', ()=>{-->
<!--                    if(tariff.value == ''){-->
<!--                            tariff.value = 0;-->
<!--                        }-->
<!--                    full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)-->
<!--    })-->

<!--    insurance.addEventListener('input', ()=>{-->
<!--                    if(insurance.value == ''){-->
<!--                            insurance.value = 0;-->
<!--                        }-->
<!--                    full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)-->
<!--    })-->

<!--    package_price.addEventListener('input', ()=>{-->
<!--                    if(package_price.value == ''){-->
<!--                            package_price.value = 0;-->
<!--                        }-->
<!--                    full_price.value = (parseFloat(tariff.value) +  parseFloat(insurance.value) +  parseFloat(package_price.value)).toFixed(2)-->
<!--    })-->

<!--    volume.addEventListener('input', ()=>{-->
<!--                    const volume_data = volume.value-->
<!--                    console.log(volume_data)-->
<!--                    density.value = parseFloat((weight.value / volume.value).toFixed(2))-->
<!--    })-->
<!--    weight.addEventListener('input', ()=>{-->
<!--                    const volume_data = volume.value-->
<!--                    console.log(volume_data)-->
<!--                    density.value = parseFloat((weight.value / volume.value).toFixed(2))-->
<!--    })-->

<!--};-->


    $('[name="logistics"]').on( "mouseenter", function(e) {
            var show_info = $(this).attr('rel');
            $("#show_info")
                .css("display", "block")
                .animate({ opacity: 1 }, 198);
            if (e.clientX > 700) {
                    $('#show_info').css({'left': e.clientX - 700, 'top': e.clientY + 10});
                    }
            else {
            $('#show_info').css({'left': e.clientX + 10, 'top': e.clientY + 10});
            }
    $.ajax({
            type        : 'POST',
            url         : "{% url 'sendings:show_logistic_info' %}",
            data: {
                id: $(this).attr('value'),
                csrfmiddlewaretoken: '{{ csrf_token }}'
                },

            success:function(response){
               var card_image = '<div class="row">' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Маркировка: ' + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + response.marker + '</p>' +
                                '</div>' +
                                '</div>' + '<hr>' +

                                '<div class="row">' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Вес: ' + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + response.weight + ' кг.' + '</p>' +
                                '</div>' +
                                '</div>' + '<hr>' +

                                '<div class="row">' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Объем: ' + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + response.volume + ' м<sup>3</sup>' + '</p>' +
                                '</div>' +
                                '</div>' + '<hr>' +

                                '<div class="row">' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Плотность: ' + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + response.density + '</p>' +
                                '</div>' +
                                '</div>' + '<hr>' +

                                '<div class="row">' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Стоимость страховки: ' + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + response.insurance + ' $' + '</p>' +
                                '</div>' +
                                '</div>' + '<hr>' +

                                '<div class="row">' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Стоимость доставки: ' + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + response.delivery_price + ' $' + '</p>' +
                                '</div>' +
                                '</div>' + '<hr>' +

                                '<div class="row">' +
                                '<div class="col">' +
                                '<p class="p-size">' + 'Стоимость товаров: ' + '</p>' +
                                '</div>' +
                                '<div class="col">' +
                                '<p class="p-size">' + response.products_price + ' ¥' + '</p>' +
                                '</div>' +
                                '</div>'


                $("#show_info").empty();
                $('#show_info').append(card_image);

          },
    });
});


$('[name="logistics"]').on( "mouseout", function() {
            $("#show_info").css("display", "none");
            $("#show_info").empty();
});


   $('[name="logistics"]').click(function() {
    var checked_paid = $(this).is(':checked');
    const order_price = document.getElementById('id_order_price')
    const weight = document.getElementById('id_weight')
    const volume = document.getElementById('id_volume')
    const places = document.getElementById('id_places')
    id_places
    $.ajax({

        type: "POST",
        url: "{% url 'sendings:get_info' %}",
        data: { checked: checked_paid,
                id: $(this).attr('value'),
                csrfmiddlewaretoken: '{{ csrf_token }}'},

        success: function(response) {
               if (checked_paid) {
                      order_price.value = parseFloat(parseFloat(order_price.value) + parseFloat(response.price)).toFixed(2)
                      weight.value = parseFloat(parseFloat(weight.value) + parseFloat(response.weight)).toFixed(2)
                      volume.value = parseFloat(parseFloat(volume.value) + parseFloat(response.volume)).toFixed(3)
                      places.value = Number(parseFloat(places.value) + parseFloat(response.places))
                    } else {
                      order_price.value = parseFloat(parseFloat(order_price.value) - parseFloat(response.price)).toFixed(2)
                      weight.value = parseFloat(parseFloat(weight.value) - parseFloat(response.weight)).toFixed(2)
                      volume.value = parseFloat(parseFloat(volume.value) - parseFloat(response.volume)).toFixed(3)
                      places.value = Number(parseFloat(places.value) - parseFloat(response.places))
                    }
        },

        error: function() {
            console.log('it broke');
        },
    });
});

$("input").focus(function(){
  $(this).select();
});
<!--</script>-->
{% endblock %}