crm/clients/urls.py
from django.urls import path

from clients import views
from clients.views import ClientDetail, delete_comment

app_name = 'clients'

urlpatterns = [
    path('clients/', views.ClientsListView.as_view(), name='home'),
    path('clients/my_clients', views.MyClientsListView.as_view(), name='my_clients'),
    path('clients/active_clients', views.ActiveClientsListView.as_view(), name='active'),
    path('clients/update_client/<int:client_id>/', views.UpdateClient.as_view(), name='upd'),
    path('clients/addclient/', views.AddClient.as_view(), name='addclient'),
    path("clients/<int:client_id>/", ClientDetail.as_view(), name='detail_client'),
    path('clients/delete_comment/<int:pk>/', delete_comment, name='del')
]

crm/crm/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls', namespace='login')),
    path('manager/', include('core.urls', namespace='core')),
    path('sendings/', include('sendings.urls', namespace='sendings')),
    path('call/', include('clients.urls', namespace='clients')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/clients/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from core.models import Clients


class Comments(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Менеджер')
    client = models.ForeignKey(Clients, on_delete=models.SET_NULL, null=True, verbose_name='Клиент')
    comment = models.TextField(verbose_name='Комментарий', blank=True)
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-id']

    def __str__(self):
        """
        String for representing the Model object.
        """
        if self.owner:
            return self.owner.username
        else:
            return 'без имени'

    def get_absolute_url(self):
        return reverse('comment', kwargs={'comment_id': self.pk})

crm/clients/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.forms import ModelForm

from clients.models import Comments
from core.models import  Clients
from django import forms


class AddClientForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'whiteForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'submit_survey'

        self.helper.add_input(Submit('submit', 'Submit'))
        self.fields["name"].widget.attrs.update({"class": "form__field"})
        self.fields["phone"].widget.attrs.update(
            {'placeholder': 'Номер телефона в формате +7...'})
        self.fields["messanger"].widget.attrs.update(
            {'placeholder': 'Поле для заметок. Например номер wechat или whatsapp...'})

    class Meta:
        model = Clients
        fields = '__all__'
        exclude = ('owner', 'comment', 'deposit')


class FilterName(forms.Form):
    client = forms.CharField(label='Клиент', max_length=200)


class CommentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'whiteForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'submit_survey'

        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Comments
        fields = '__all__'
        exclude = ('owner', 'client')

crm/clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView
from django.views.generic.edit import FormMixin
from django_filters.views import FilterView

from clients.filters import ClientFilter
from clients.forms import AddClientForm, CommentForm
from clients.models import Comments
from core.models import Clients


class ClientsListView(LoginRequiredMixin, FilterView):
    model = Clients
    paginate_by = 16
    template_name = 'clients/clients_list.html'
    filterset_class = ClientFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ClientFilter.form
        context['title'] = 'Список клиентов'
        return context

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Clients.objects.filter(result=True)
        else:
            return Clients.objects.filter(result=True).filter(owner=self.request.user)


class ActiveClientsListView(ClientsListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ClientFilter.form
        context['title'] = 'Мои клиенты'
        return context

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Clients.objects.filter(result=True)
        else:
            return Clients.objects.filter(result=True).filter(owner=self.request.user)


class MyClientsListView(ClientsListView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ClientFilter.form
        context['title'] = 'Мои клиенты'
        return context

    def get_queryset(self):
        return Clients.objects.filter(owner=self.request.user)


class AddClient(LoginRequiredMixin, CreateView):
    form_class = AddClientForm
    template_name = 'clients/addclient.html'
    success_url = reverse_lazy('clients:home')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить клиента'
        return context


class UpdateClient(LoginRequiredMixin, UpdateView):
    model = Clients
    form_class = AddClientForm
    pk_url_kwarg = 'client_id'
    template_name = 'clients/updateclient.html'

    def get_success_url(self):
        return reverse('clients:home')


class ClientDetail(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'clients/detailclient.html'
    model = Clients
    pk_url_kwarg = 'client_id'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('clients:detail_client', kwargs={'client_id': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super(ClientDetail, self).get_context_data(**kwargs)
        orders_list = self.object.client_orders.all()
        orders = [{'order': order, 'products': order.product.all()} for order in orders_list]

        context['comments'] = Comments.objects.filter(client=self.object).order_by('date_create')
        context['orders'] = orders
        context['form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.client = self.object
        form.save()
        return super(ClientDetail, self).form_valid(form)


def delete_comment(request, pk):
    comment = Comments.objects.get(pk=pk)
    client = comment.client.pk
    comment.delete()
    return redirect('clients:detail_client', client)

crm/templates/clients/addclient.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}

{% if form %}
    <div class="container" style="background-color:#adbbcc; padding:5%;border-radius:3%;">
    <form action="{% url 'core:addclient' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {{ form|crispy }}
        <button class="btn btn-light" type="submit">Сохранить</button>
    </form>
    </div>
{% endif %}
{% endblock %}

crm/templates/clients/clients_list.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row" style="align-items: flex-start;">

        <div class="col-lg-12 secondcolor pad_list" style="background-color:#f5f5f5;">
                <br>
                <div class="row">
                    <div class="col-3">
                        <button class="btn btn-outline-secondary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">Фильтры</button>
                    </div>
                    <div class="col-9">
                        <h2 style="text-align:end;">{{title}}</h2>
                    </div>
                </div>

                <div class="offcanvas offcanvas-end" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
                <div class="offcanvas-header">
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
                </div>
                <div class="offcanvas-body">
                <form action="" method="get">
                {{ filter.form|crispy }}
                <button class="btn btn-outline-secondary" type="submit">Поиск</button>
            </form>
                </div>
                </div>
            <hr>
        {% if object_list %}
        <div class="row" style="margin-top:1%; margin-bottom:1%;">
            <div class="col center"><p class="p-size">Клиент</p></div>
            <div class="col center"><p class="p-size">Номер телефона</p></div>
            <div class="col center"><p class="p-size">Дата оформления</p></div>
            <div class="col center"><p class="p-size">Менеджер</p></div>
            <div class="col center"><p class="p-size">Статус</p></div>
        </div>
          {% for client in object_list %}

          {% if client.result == True %}
            <a href="{% url 'clients:detail_client' client.pk %}">
                <div class="row list-height" style="font-weight: 700; border-color:#ead1dc; margin-top:1%; margin-bottom:1%; background-color:#fff;">
                    <div class="col center"><p class="p-size">{{client}}</p></div>
                    <div class="col center"><p class="p-size">{% if client.phone %}{{client.phone}}{% else %}Не указан{% endif %}</p></div>
                    <div class="col center"><p class="p-size">{{client.date_create}}</p></div>
                    <div class="col center"><p class="p-size">{{client.owner}}</p></div>
                    <div class="col center"><h3 style="margin-top:3%">&#129299;</h3></div>

                </div>
            </a>

          {% else %}
            <a href="{% url 'clients:detail_client' client.pk %}">
                <div class="row list-height" style="font-weight: 700; border-color:#bbddfd; margin-top:1%; margin-bottom:1%; background-color:#fff;">
                    <div class="col"><p>{{client}}</p></div>
                    <div class="col"><p>{{client.phone}}</p></div>
                    <div class="col"><p>{{client.date_create}}</p></div>
                    <div class="col"><h3 style="margin-top:3%">&#128545;</h3></div>
                </div>
            </a>
          {% endif %}
            {% endfor %}
        {% else %}
    <h3>Нет клиентов.</h3>
    </div>
    </div>
    {% endif %}
{% endblock %}

crm/templates/clients/detailclient.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
  <div class="row">
      <hr>
      <div class="col-6"><p style="font-size: calc(16px + 8 * (100vw / 1280)); font-weight: 700;">{{ object.name }} {% if object.surname %}{{ object.surname }}{% endif %}</p></div>
      <div class="col-5"><p style="font-size: calc(16px + 8 * (100vw / 1280)); font-weight: 700;">Остаток на счете: {{ object.deposit }}</p></div>
      <div class="col"><button id="order_list" class="btn btn-secondary" type="button">Заказы</button></div>
  </div>
  <div class="col"><p><strong>Телефон: </strong>{% if object.phone %}{{ object.phone }}{% else %}Не указан{% endif %}</p></div>
        <div class="col messanger"><p>{{object.messanger}}</p></div>
  <div class="col-3" style="margin-top:5%;"><a href="{% url 'clients:upd' object.pk %}" class="btn_edit">Изменить</a></div>
    <hr>
    {% if comments %}
          {% for comment in comments %}
            <div class="col list-height" style="border-color:#bbddfd; margin-top:1%; margin-bottom:1%; background-color:#fff;">
                <div class="row hei" style="margin:0;">
                    <div class="col-3" style="background-color:#f2feff; margin-left: auto; margin-right: auto;">
                        <div class="row" style="margin-left: auto; margin-right: auto;">
                            <p style="font-size: calc(16px + 8 * (100vw / 1280)); font-weight: 700;">{{ comment.owner.username }}</p>
                        </div>
                        <div class="row" style="margin-left: auto; margin-right: auto;">
                            <p style="font-size: calc(12px + 8 * (100vw / 1280));">{{ comment.date_create }}</p>
                        </div>
                    </div>
                    <div class="col-8">
                        <p style="font-size:1rem;">{{ comment.comment }}</p>
                    </div>

                    <div class="col-1">
                        {% if comment.owner == request.user %}
                        <a href="{% url 'clients:del' comment.pk %}">удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
          {% endfor %}
    {% else %}
        <p style="font-size: calc(16px + 8 * (100vw / 1280)); font-weight: 700;">Комментариев пока не оставляли.</p>
    {% endif %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {{ form|crispy }}
        <button class="btn btn-secondary" type="submit">Сохранить</button>
    </form>
    </div>

<div id="modal_order_list" style="display:none;">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modalBodyWrapper">
          {% for order in orders %}
          <div class="flex-wrap" style="background:#dfdfdf;padding:0;">
          <h2 align="center" style="padding-left:5px;">Заказ: {{order.order}}</h2>
          <h2 align="center" style="padding-right:5px;">Дата: {{order.order.date_create}}</h2>
          </div>
              {% for product in order.products %}
              <p>Продукт: {{product}}</p>
                <div class="flex-wrap-s">
                {% for img in product.images.all %}
              <img src="{{ img.url }}" class="image-detail">
                    {% load thumbnail %}
                        {% thumbnail img.image "128x64" as im %}
                    <!-- Modal -->
                        <div style="border: 2px solid #d0d0d0;">
                            {% if img.image %}
                            <a href="{{ img.image.url }}" data-bs-toggle="modal" data-bs-target="#img_{{img.pk}}">
                                  <img src="{{ im.url }}" class="image-detail">
                            </a>
                        </div>
                                        <div class="modal fade" id="img_{{img.pk}}" aria-labelledby="img_{{img.pk}}" aria-hidden="true">
                                          <div class="modal-dialog modal-xl">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="exampleModalLabel">{{product}}</h1>
                                              </div>
                                              <div class="modal-body">
                                                <img src="{{ img.image.url }}">
                                              </div>
                                              <div class="modal-footer">
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                            {% endif %}
                    {% endthumbnail %}
                {% endfor %}
                {% for img in product.packed_images.all %}
                <img src="{{ img.url }}" class="image-detail">
                    {% load thumbnail %}
                        {% thumbnail img.image "128x64" as im %}
                    <!-- Modal -->
                        <div style="border: 2px solid #d0d0d0;">
                            {% if img.image %}
                            <a href="{{ img.image.url }}" data-bs-toggle="modal" data-bs-target="#packed_img_{{img.pk}}">
                                  <img src="{{ im.url }}" class="image-detail">
                            </a>
                        </div>
                                        <div class="modal fade" id="packed_img_{{img.pk}}" aria-labelledby="img_{{img.pk}}" aria-hidden="true">
                                          <div class="modal-dialog modal-xl">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h1 class="modal-title fs-5" id="exampleModalLabel">{{product}}</h1>
                                              </div>
                                              <div class="modal-body">
                                                <img src="{{ img.image.url }}">
                                              </div>
                                              <div class="modal-footer">
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                            {% endif %}
                    {% endthumbnail %}
                {% endfor %}
                </div>
              {% endfor %}
          <hr>
          {% endfor %}
      </div>
      <div class="modal-footer">
          <button name='close_modal' class="floating-button" type="button">закрыть</button>
      </div>
    </div>
  </div>
</div>

<script defer>
    $("#order_list").on( "click", function(e) {
        console.log('Нажали');
            $("#modal_order_list")
                .css("display", "block")
                .animate({ opacity: 1 }, 198);
    });

    $('button[name="close_modal"]').on( "click", function(e) {
            $("#modal_order_list")
                .css("display", "none")
                .animate({ opacity: 1 }, 198);
    });
</script>

{% endblock %}

crm/templates/clients/updateclient.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if form %}
    <div class="col secondcolor" style="padding-left: 1%; padding-right: 1%; background-color:#f5f5f5;">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {{ form|crispy }}
        <button class="btn btn-secondary" type="submit">Сохранить</button>
    </form>
    </div>
{% endif %}
{% endblock %}